# Generated by Django 2.1.4 on 2018-12-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181215_2016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifyCode',
            new_name='MobileVerifyCode',
        ),
    ]
