# Generated by Django 2.1.4 on 2018-12-18 13:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181216_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='media/default/default_userprofile.jpg', help_text='头像', null=True, upload_to=users.models.upload_profile_image, verbose_name='头像'),
        ),
    ]
