# Generated by Django 2.1.4 on 2018-12-18 16:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/default/default_userprofile.png', help_text='头像', upload_to=users.models.upload_profile_image, verbose_name='头像'),
        ),
    ]
