# Generated by Django 2.1.4 on 2018-12-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181218_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, default='', help_text='邮箱', max_length=50, verbose_name='邮箱'),
        ),
    ]
