# Generated by Django 2.1.4 on 2018-12-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181219_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='update_email',
            field=models.EmailField(default='', max_length=50, verbose_name='修改后邮箱'),
        ),
    ]
